id: P010586
initial_creation_type: ocr
source_metadata:
  id: bdr:W28780
  title: ལམ་འབྲས་ལམ་རིམ་སྨོན་ལམ
  author: ''
  volumes:
    410693321bdb4591b9b215c30c41cd63:
      image_group_id: I1CZ1036
      title: ''
      volume_number: 1
      total_pages: 36
